### ISSUE TITLE
I cannot find '2017-12-14.json' file

### ISSUE THREAD

**Issue by Graceqi** [stanford-futuredata/tasti#1]
Can the author provide the documents

**Comment by ddkang** [comment]
2017-12-14.json should be automatically generated when using the SWAG package to load the videos. If this is not happening, please provide the full error message.

**Comment by Graceqi** [comment]
But when I run "night_street_offline.py" ,there is no json file generated.

**Comment by BiaoWang1997** [comment]
When I run swag.VideoCapture("~/data/2017-12-14")  it raise FileNotFoundError:  No such file or directory: '~/data/2017-12-14'
but I replace ~ with /home/USERNAME , it runs correctly.  Is there any bugs in swag?

**Comment by Graceqi** [comment]
I find if put 'self.cap = swag.VideoCapture(self.video_fp)' before ' self.video_metadata = json.load(open(self.video_fp + '.json', 'r'))' in class VideoDataset ,it will solve the probloem.

**Comment by ghost** [comment]
When I run swag.VideoCapture(" ~ /data/2017-12-14") it raise FileNotFoundError: No such file or directory: ' ~ /data/2017-12-14'
but I replace ~ with /home/USERNAME , it runs correctly. Is there any bugs in swag?

**Comment by ddkang** [comment]
It looks like there's a space in your file path.

**Comment by ddkang** [comment]
> I find if put 'self.cap = swag.VideoCapture(self.video_fp)' before ' self.video_metadata = json.load(open(self.video_fp + '.json', 'r'))' in class VideoDataset ,it will solve the probloem.

Thanks, could you file a pull request with the code?

**Comment by BiaoWang1997** [comment]
> It looks like there's a space in your file path.

in code file there is no space

**Comment by jtguibas** [comment]
Fixed in PR #2
